@echo off
rem SPDX-FileCopyrightText: 2026 The Tether Authors <bioedca@u.northwestern.edu>
rem SPDX-License-Identifier: GPL-3.0-or-later
rem
rem constructor post_install (Windows .exe / NSIS) — ADR-0049, PRD Section 9 M9.
rem
rem Runs AFTER all conda packages and the bundled wheels are linked into the
rem prefix. Offline-installs the three non-conda wheels (no network: --no-index
rem --no-deps; deps come from the bundled conda envs) and wires the isolated
rem sidecar interpreter for conda-activated launches. Both runtime stacks are
rem constructor `extra_envs` (ADR-0049): the GUI/tether stack in envs\tether and
rem the tMAVEN sidecar in envs\sidecar; `base` is only the python+conda bootstrap.
setlocal

set "WHEELHOUSE=%PREFIX%\wheelhouse"
set "TETHER_PY=%PREFIX%\envs\tether\python.exe"
set "SIDECAR_PY=%PREFIX%\envs\sidecar\python.exe"

rem tether wheel -> the GUI env (PySide6/napari/current-numpy). A `for` over an
rem unmatched glob runs zero iterations and leaves errorlevel untouched, so guard
rem the missing-wheel case explicitly (unlike post_install.sh, where the literal
rem unmatched glob reaches pip and fails under `set -e`).
if not exist "%WHEELHOUSE%\tether-*.whl" (
  echo ERROR: tether wheel not found in %WHEELHOUSE%
  exit /b 1
)
for %%W in ("%WHEELHOUSE%\tether-*.whl") do (
  "%TETHER_PY%" -m pip install --no-index --no-deps "%%W"
  if errorlevel 1 exit /b 1
)

rem setuptools<81 -> the sidecar env, BEFORE tMAVEN. tMAVEN's maven_class.__init__
rem does `import pkg_resources`, which setuptools 81.0.0 DEPRECATED and 82.0.0 REMOVED,
rem and the sidecar lock resolves setuptools 82.0.1 — so without this the env builds
rem cleanly and then dies at the first idealization (issue #212). `<81` rather than
rem `<82` is the bound setuptools' own deprecation warning names.
rem scripts/setup_sidecar.py applies the same pin (SETUPTOOLS_PIN) on the source path;
rem this is the installer's equivalent.
rem
rem pip is given the wheel by PATH, not by requirement spec, so it downgrades the conda
rem setuptools rather than reporting "already satisfied".
if not exist "%WHEELHOUSE%\setuptools-*.whl" (
  echo ERROR: setuptools wheel not found in %WHEELHOUSE%
  exit /b 1
)
for %%W in ("%WHEELHOUSE%\setuptools-*.whl") do (
  "%SIDECAR_PY%" -m pip install --no-index --no-deps "%%W"
  if errorlevel 1 exit /b 1
)

rem tMAVEN wheel -> the ISOLATED sidecar env (PyQt5/numpy<2); never the GUI env.
if not exist "%WHEELHOUSE%\tmaven-*.whl" (
  echo ERROR: tmaven wheel not found in %WHEELHOUSE%
  exit /b 1
)
for %%W in ("%WHEELHOUSE%\tmaven-*.whl") do (
  "%SIDECAR_PY%" -m pip install --no-index --no-deps "%%W"
  if errorlevel 1 exit /b 1
)

rem Best-effort: point the app at its bundled sidecar interpreter when the GUI env
rem is conda-activated. envs\sidecar is a sibling of envs\tether, so resolve it
rem relative to %%CONDA_PREFIX%% at activation time (a prefix-relative app-side
rem default is the more robust follow-up, ADR-0049).
set "ACT_D=%PREFIX%\envs\tether\etc\conda\activate.d"
if not exist "%ACT_D%" mkdir "%ACT_D%"
> "%ACT_D%\tether-sidecar.bat" echo set "TETHER_SIDECAR_PYTHON=%%CONDA_PREFIX%%\..\sidecar\python.exe"

rem --- Launchers (ADR-0051) -------------------------------------------------------
rem envs\tether\Scripts is NEVER on PATH: initialize_conda and register_python are
rem both false, so the installer deliberately does not touch the user's shell or
rem registry. Without the shims below there is no way to start Tether except by
rem typing an env-relative absolute path, and `tether --version` — the documented
rem install-verification step — fails.
rem
rem One stable, documented directory (%PREFIX%\bin) holds both launchers so the
rem install guide can name a SINGLE path to put on PATH. The installer does NOT edit
rem PATH itself: `setx` silently TRUNCATES PATH beyond 1024 characters, which is not
rem recoverable by documentation, whereas adding a directory is a one-liner.
set "BIN_D=%PREFIX%\bin"
if not exist "%BIN_D%" mkdir "%BIN_D%"
> "%BIN_D%\tether.bat" echo @echo off
>>"%BIN_D%\tether.bat" echo rem Generated by the Tether installer (ADR-0051).
>>"%BIN_D%\tether.bat" echo "%PREFIX%\envs\tether\Scripts\tether.exe" %%*
> "%BIN_D%\tether-gui.bat" echo @echo off
>>"%BIN_D%\tether-gui.bat" echo rem Generated by the Tether installer (ADR-0051).
>>"%BIN_D%\tether-gui.bat" echo start "" "%PREFIX%\envs\tether\Scripts\tether-gui.exe" %%*

rem Start Menu shortcut for the GUI. menuinst is not usable here: it attaches
rem shortcuts to a CONDA package, and `tether` is an offline-pip-installed wheel, so
rem menu_packages stays [] and the shortcut is created directly. Targets the
rem console-less tether-gui.exe produced by [project.gui-scripts] — a `scripts`
rem entry point would flash a terminal window on every launch.
rem Paths are handed to PowerShell through the ENVIRONMENT, never interpolated into
rem its source: a single apostrophe anywhere in %APPDATA% or %PREFIX% (e.g. a user
rem named O'Brien) would close the single-quoted literal early and the shortcut would
rem silently fail to a warning. $env:VAR carries the value verbatim, quotes and all.
set "SM_D=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Tether"
if not exist "%SM_D%" mkdir "%SM_D%"
set "TETHER_LNK=%SM_D%\Tether.lnk"
set "TETHER_GUI_EXE=%PREFIX%\envs\tether\Scripts\tether-gui.exe"
set "TETHER_GUI_WD=%PREFIX%\envs\tether"
powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command ^
  "$s=(New-Object -ComObject WScript.Shell).CreateShortcut($env:TETHER_LNK);" ^
  "$s.TargetPath=$env:TETHER_GUI_EXE;" ^
  "$s.WorkingDirectory=$env:TETHER_GUI_WD;" ^
  "$s.Description='Tether - single-molecule FRET analysis';" ^
  "$s.Save()" 2>nul
if errorlevel 1 echo WARNING: could not create the Start Menu shortcut; launch via %BIN_D%\tether-gui.bat

rem Drop the staged wheels; the environments now own the installed packages.
del "%WHEELHOUSE%\tether-*.whl" "%WHEELHOUSE%\tmaven-*.whl" "%WHEELHOUSE%\setuptools-*.whl" 2>nul
exit /b 0
