#!/bin/sh
# SPDX-FileCopyrightText: 2026 The Tether Authors <bioedca@u.northwestern.edu>
# SPDX-License-Identifier: GPL-3.0-or-later
#
# constructor post_install (Unix: Linux .sh + macOS .pkg) — ADR-0049, PRD §9 M9.
#
# Runs AFTER all conda packages and the bundled wheels are linked into the prefix.
# It offline-installs the two non-conda wheels (no network: --no-index --no-deps;
# every runtime dependency already comes from the bundled conda envs) and wires the
# isolated sidecar interpreter for conda-activated launches. POSIX sh only.
#
# Both runtime stacks are constructor `extra_envs` (ADR-0049): the GUI/`tether`
# stack lives in envs/tether, the tMAVEN sidecar in envs/sidecar. `base` is only the
# python+conda bootstrap that constructor requires for extra_envs — nothing app is
# installed there.
set -e

WHEELHOUSE="$PREFIX/wheelhouse"
TETHER_PY="$PREFIX/envs/tether/bin/python"
SIDECAR_PY="$PREFIX/envs/sidecar/bin/python"

# tether wheel -> the GUI env (PySide6/napari/current-numpy).
"$TETHER_PY" -m pip install --no-index --no-deps "$WHEELHOUSE"/tether-*.whl

# tMAVEN wheel -> the ISOLATED sidecar env (PyQt5/numpy<2); never the GUI env.
"$SIDECAR_PY" -m pip install --no-index --no-deps "$WHEELHOUSE"/tmaven-*.whl

# Best-effort: point the app at its bundled sidecar interpreter when the GUI env is
# conda-activated (tether.idealize.driver reads $TETHER_SIDECAR_PYTHON). envs/sidecar
# is a sibling of envs/tether, so resolve it relative to $CONDA_PREFIX at activation
# time (the heredoc is single-quoted, so the expansion is deferred, not baked in). A
# prefix-relative app-side default is the more robust follow-up (ADR-0049).
ACT_D="$PREFIX/envs/tether/etc/conda/activate.d"
mkdir -p "$ACT_D"
cat > "$ACT_D/tether-sidecar.sh" <<'EOF'
export TETHER_SIDECAR_PYTHON="$(dirname "$CONDA_PREFIX")/sidecar/bin/python"
EOF

# --- Launchers (ADR-0051) --------------------------------------------------------
# envs/tether/bin is NEVER on PATH: initialize_conda/initialize_by_default are false,
# so the installer deliberately does not touch the user's shell. Without the shims
# below there is no way to start Tether except by typing an env-relative absolute
# path, and `tether --version` — the documented install-verification step — fails.
#
# One stable, documented directory ($PREFIX/bin) holds both launchers, so the install
# guide can name a SINGLE path to put on PATH. The installer does not edit PATH
# itself: `setx` silently truncates PATH beyond 1024 characters on Windows, and
# rewriting a user's shell rc is equally invasive. Adding the directory is a
# documented one-liner; breaking someone's PATH is not recoverable by documentation.
BIN_D="$PREFIX/bin"
mkdir -p "$BIN_D"
for _cmd in tether tether-gui; do
  cat > "$BIN_D/$_cmd" <<EOF
#!/bin/sh
# Generated by the Tether installer (ADR-0051). Forwards to the pinned GUI env.
exec "$PREFIX/envs/tether/bin/$_cmd" "\$@"
EOF
  chmod +x "$BIN_D/$_cmd"
done

# Linux desktop entry so the shell is launchable from the applications menu. macOS
# .pkg installs get the shims above only — a proper .app bundle is separate work
# (ADR-0051). `uname` rather than a constructor selector: this is one shared script.
if [ "$(uname -s)" = "Linux" ]; then
  APPS_D="$HOME/.local/share/applications"
  mkdir -p "$APPS_D"
  cat > "$APPS_D/tether.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Tether
GenericName=single-molecule FRET analysis
Comment=Provenance-first smFRET extraction, curation and analysis
Exec=$PREFIX/envs/tether/bin/tether-gui %f
Terminal=false
Categories=Science;Biology;Education;
MimeType=application/x-tether;
EOF
  # Best-effort: a stale cache hides a brand-new entry until the next login.
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$APPS_D" >/dev/null 2>&1 || true
  fi
fi

# Drop the staged wheels; the environments now own the installed packages.
rm -f "$WHEELHOUSE"/tether-*.whl "$WHEELHOUSE"/tmaven-*.whl
