# SPDX-FileCopyrightText: 2026 The Tether Authors <bioedca@u.northwestern.edu>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Multi-curator split-file label merge-back — append-only owner-pull (PRD §5.1/§7.5/§7.10; FR-ML).

Concurrent curation is served by the **split-file path** (§7.10): a non-owner lab member browses and
curates into their *own* subset ``.tether`` (its own provenance-tagged ``/labels``, each row keyed
by the stable ``molecule_key``, §5.1) instead of writing the locked central project. This module is
the
**owner-pull** that folds those split-file human labels back into the condition-owner's canonical
project so its retrain sees them (PRD §7.5/§7.10):

* **append-only** — the contributor's human ``/labels`` rows are *appended* to the owner's
  ``/labels/table`` (never rewriting or deleting an existing row), carrying their original
  ``labeler`` / ``timestamp`` / ``source_file`` provenance so who-labeled-what survives the merge;
* **joined on** ``molecule_key`` — the stable cross-file content identity (movie ``sha256`` +
  quantized ``donor_xy``, §5.1/§7.10) is the only join key; a split-file row whose ``molecule_key``
  is absent from the owner's ``/molecules`` cannot be attributed and is **surfaced** (never silently
  dropped, §7.5), not appended;
* **weights recomputed centrally** — per-split-file stored weights are advisory and superseded by
  the owner's retrain, which recomputes every row's ``weight`` from the merged set
  (:func:`tether.project.weighting.recompute_label_weights`), so no weight reconciliation is needed
  (§5.1);
* **human-vs-human disagreement surfaces, never overwrites** — the owner's authoritative
  ``/molecules.curation_label`` is the training signal the ranker reads for human labels
  (:func:`tether.project.gbranking.weighted_training_set`). A contributor decision on a molecule the
  owner has **not** decided is *adopted*; one that **agrees** is a no-op; a **disagreement** is a
  :class:`MergeConflict` returned for a §7.4-style per-trace reconcile prompt (PRD §7.5) — the
  owner's ``curation_label`` is left untouched until a human resolves it (via the ordinary
  :func:`tether.project.labels.accept` / :func:`~tether.project.labels.reject`). Surfacing
  disagreement rather than silently majority-voting or averaging it away preserves the signal that
  annotator disagreement carries [Davani2021] and routes it through a deliberate procedure
  [Oortwijn2021].

The append is **additive data** under the M0-frozen schema (no group, dataset, dtype or field
change), and the ``curation_label`` adoption rewrites a frozen field's *value* only — so
``schema-guard`` holds (ADR-0005, ADR-0023). The two provisional (non-human) ``/labels`` sources are
the *owner's own* machine priors (regenerated by the seeding path, ADR-0038), not contributor
curation, so they are **not** pulled across a merge (their count is reported, never silently
ignored). The owner is opened ``r+``; the single-writer ``.lock`` serializing the central project
(§5.4) is the caller's concern, as for :func:`tether.project.labels.set_curation_label`.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING

from tether.io.schema import LABELS_DTYPE, TABLE
from tether.project.labels import LABEL_SOURCE_HUMAN, CurationLabel

if TYPE_CHECKING:
    from os import PathLike

    import numpy as np

    from tether.project.core import Project

    ProjectRef = Project | str | PathLike[str]

__all__ = ["MergeConflict", "MergeReport", "merge_labels"]

_MOLECULES = "molecules"
_LABELS = "labels"
_UNCURATED = int(CurationLabel.UNCURATED)

#: The frozen ``/labels`` provenance fields that identify one curation *event*. Rows equal on all
#: of them are the *same* event already pulled — the dedup key making a re-pull of the same split
#: file idempotent (append-only still holds: only genuinely new events are appended). ``weight`` and
#: ``condition_id`` are excluded: ``weight`` is advisory/recomputed (§5.1) and ``condition_id`` is
#: rewritten to the owner's authoritative value on append, so neither identifies the event.
_EVENT_FIELDS = ("molecule_key", "labeler", "timestamp", "source_file", "source", "label_value")


def _project_path(project: ProjectRef) -> Path:
    from tether.project.core import Project as _Project  # noqa: PLC0415

    return project.path if isinstance(project, _Project) else Path(project)


def _to_str(value: object) -> str:
    """Decode an h5py variable-length string field (``bytes`` or ``str``)."""
    return value.decode("utf-8") if isinstance(value, bytes) else str(value)


def _event_key(row: np.ndarray) -> tuple:
    """The provenance-identity tuple of one ``/labels`` row (its :data:`_EVENT_FIELDS` values)."""
    return tuple(int(row[f]) if f == "label_value" else _to_str(row[f]) for f in _EVENT_FIELDS)


@dataclass(frozen=True)
class MergeConflict:
    """A human-vs-human disagreement on one molecule (PRD §7.4/§7.5 reconcile prompt).

    The contributor's current human decision differs from the owner's current human decision on the
    same ``molecule_key``. The merge **records** the contributor's event in the owner's append-only
    ``/labels`` (audit + provenance) but leaves the owner's authoritative ``curation_label``
    untouched — the disagreement is surfaced here for a deliberate per-trace resolution, never
    silently overwritten [Davani2021, Oortwijn2021]. A resolution is the ordinary owner action
    (:func:`tether.project.labels.accept` / :func:`~tether.project.labels.reject`).
    """

    molecule_key: str
    #: The owner's current ``curation_label`` (a signed
    #: :class:`~tether.project.labels.CurationLabel` code, ``ACCEPT`` / ``REJECT``), left unchanged.
    owner_label: int
    #: The contributor's current human decision (``ACCEPT`` / ``REJECT``) that disagrees with it.
    contributor_label: int
    #: The contributor who made that decision (the ``labeler`` on their latest ``/labels`` row).
    contributor_labeler: str
    #: The split file that decision came from (the ``source_file`` on that row).
    contributor_source_file: str


@dataclass(frozen=True)
class MergeReport:
    """The outcome of an append-only owner-pull merge (PRD §5.1/§7.5/§7.10) — fully itemized.

    Every source row is accounted for (appended, deduplicated, unmatched, ambiguous, or non-human)
    and every classified molecule lands in exactly one of ``adopted`` / ``agreements`` /
    ``conflicts`` — nothing is silently dropped (§7.5).
    """

    #: Count of contributor **human** ``/labels`` rows appended to the owner's log (genuinely new
    #: events on a matched ``molecule_key``).
    appended: int
    #: ``molecule_key`` values whose owner ``curation_label`` was **set** from the contributor's
    #: decision — molecules the owner had not yet curated (``UNCURATED``). Sorted, deduplicated.
    adopted: tuple[str, ...]
    #: ``molecule_key`` values where the contributor's decision **matched** the owner's existing one
    #: (no state change). Sorted, deduplicated.
    agreements: tuple[str, ...]
    #: Surfaced human-vs-human disagreements (owner state left untouched; §7.4 reconcile), one per
    #: conflicting ``molecule_key``.
    conflicts: tuple[MergeConflict, ...]
    #: Distinct source ``molecule_key`` values absent from the owner's ``/molecules`` (cannot be
    #: attributed → not appended, surfaced instead of silently dropped). Sorted.
    unmatched: tuple[str, ...]
    #: Distinct source ``molecule_key`` values that map to **more than one** owner ``condition_id``
    #: (a same-sha cross-condition coordinate collision, §7.10) — an ambiguous label scope refused
    #: like :func:`tether.project.labels.set_curation_label` does (not appended, not adopted,
    #: surfaced). Sorted.
    ambiguous: tuple[str, ...]
    #: Count of ``/labels`` rows skipped because their ``source`` is **not** ``"human"`` — the
    #: two provisional seed priors are the owner's own, not contributor curation (ADR-0038).
    skipped_non_human: int
    #: Count of contributor human rows skipped as **already present** in the owner's log (idempotent
    #: re-pull of the same split file — same :data:`_EVENT_FIELDS` provenance).
    skipped_duplicate: int
    #: Count of ``/labels`` rows whose ``weight`` was recomputed centrally after the append (``0``
    #: when ``recompute_weights=False``).
    weights_recomputed: int

    @property
    def n_conflicts(self) -> int:
        """Number of surfaced human-vs-human conflicts awaiting reconcile."""
        return len(self.conflicts)


def merge_labels(
    owner: ProjectRef,
    source: ProjectRef,
    *,
    recompute_weights: bool = True,
) -> MergeReport:
    """Pull a split file's human labels into the owner project (append-only, joined on key).

    The condition-owner's merge-back (PRD §7.5/§7.10): the contributor's human ``/labels`` rows are
    **appended** to ``owner``'s ``/labels/table`` (never rewriting an existing row), joined on the
    stable ``molecule_key`` (§5.1). For each matched molecule the contributor's *current* human
    decision (their latest human ``/labels`` event) is compared with the owner's authoritative
    ``curation_label``:

    * owner **uncurated** → the decision is **adopted** into the owner's ``curation_label`` (so the
      ranker trains on it — :func:`tether.project.gbranking.weighted_training_set` reads human
      labels from ``curation_label``);
    * owner **agrees** → a no-op;
    * owner **disagrees** → a :class:`MergeConflict` is returned and the owner's ``curation_label``
      is left **untouched** for a §7.4-style reconcile (never silently overwritten).

    Then — unless ``recompute_weights=False`` — every ``/labels`` weight recomputes centrally from
    the merged set (:func:`tether.project.weighting.recompute_label_weights`), so per-split-file
    weights are superseded (§5.1). Re-pulling the same split file is **idempotent**: rows already
    present (same provenance) are skipped, and adoption/agreement are unchanged on a second run.

    Only ``source == "human"`` rows are pulled; the provisional seed sources are the owner's own
    priors (ADR-0038) and are counted, not merged. A source row whose ``molecule_key`` is not in the
    owner's ``/molecules`` is surfaced in :attr:`MergeReport.unmatched`; one whose ``molecule_key``
    maps to more than one owner ``condition_id`` (an ambiguous scope, §7.10) is surfaced in
    :attr:`MergeReport.ambiguous` and refused — like
    :func:`tether.project.labels.set_curation_label` — neither appended nor adopted.

    Parameters
    ----------
    owner:
        The condition-owner's canonical ``.tether`` (a :class:`~tether.project.core.Project` or
        path), opened ``r+``.
    source:
        A contributor's split/subset ``.tether`` to pull human labels from (opened read-only).
    recompute_weights:
        Recompute the owner's ``/labels`` weights after the append (default ``True``). Set ``False``
        to defer the central recompute to an explicit retrain.

    Returns
    -------
    MergeReport
        A full itemization of the merge (appended / adopted / agreements / conflicts / unmatched /
        skipped).

    Raises
    ------
    KeyError
        ``owner`` or ``source`` has no ``/labels`` or ``/molecules`` group (not an extracted
        ``.tether``).
    """
    import h5py  # noqa: PLC0415
    import numpy as np  # noqa: PLC0415

    owner_path = _project_path(owner)
    source_path = _project_path(source)

    # --- read the contributor's split file (read-only) -----------------------------------------
    with h5py.File(source_path, "r") as sf:
        try:
            src_rows = sf[_LABELS][TABLE][:]
        except KeyError as exc:
            raise KeyError(f"{source_path.name} has no /labels group") from exc
        if _MOLECULES not in sf:
            raise KeyError(f"{source_path.name} has no /molecules group")

    is_human_src = np.array(
        [_to_str(s) == LABEL_SOURCE_HUMAN for s in src_rows["source"]], dtype=bool
    )
    skipped_non_human = int(np.count_nonzero(~is_human_src))
    human_rows = src_rows[is_human_src]

    with h5py.File(owner_path, "r+") as f:
        try:
            labels_table = f[_LABELS][TABLE]
            mol_table = f[_MOLECULES][TABLE]
        except KeyError as exc:
            raise KeyError(f"{owner_path.name} has no /labels or /molecules group") from exc

        mol_keys = [_to_str(k) for k in mol_table["molecule_key"][:]]
        mol_labels = mol_table["curation_label"][:]
        mol_conditions = [_to_str(c) for c in mol_table["condition_id"][:]]
        # First matched /molecules row per key is authoritative for its condition + current decision
        # (mirrors tether.project.labels.curation_label_of); adoption updates *all* matched rows.
        owner_indices: dict[str, list[int]] = {}
        for i, key in enumerate(mol_keys):
            owner_indices.setdefault(key, []).append(i)
        owner_condition = {key: mol_conditions[idx[0]] for key, idx in owner_indices.items()}
        owner_conditions_of = {
            key: {mol_conditions[i] for i in idx} for key, idx in owner_indices.items()
        }

        # Existing event provenance in the owner log → idempotent re-pull (skip present rows).
        existing_events = {_event_key(row) for row in labels_table[:]}

        # Partition the contributor's human rows: matched-new (append) / duplicate / unmatched /
        # ambiguous.
        matched_new: list[np.ndarray] = []
        skipped_duplicate = 0
        unmatched: set[str] = set()
        ambiguous: set[str] = set()
        # Track the *latest* human decision per matched key (append order) for classification, with
        # the provenance (labeler / source_file) that made it — for a MergeConflict.
        latest_decision: dict[str, tuple[int, str, str]] = {}
        for row in human_rows:
            key = _to_str(row["molecule_key"])
            if key not in owner_indices:
                unmatched.add(key)
                continue
            if len(owner_conditions_of[key]) > 1:
                # molecule_key maps to >1 owner condition_id (a same-sha cross-condition coordinate
                # collision, §7.10): the label's condition scope is ambiguous, so refuse to attach
                # it — mirroring set_curation_label's multi-condition guard. Surface it rather than
                # silently tag one condition and adopt across both (which would inflate the
                # other condition's n_human with no /labels provenance).
                ambiguous.add(key)
                continue
            # Rewrite condition_id to the owner's authoritative value for the molecule (physical
            # molecule's condition lives on the owner's /molecules, §5.1) so the central weight
            # recompute groups the appended row correctly.
            row = row.copy()
            row["condition_id"] = owner_condition[key]
            latest_decision[key] = (
                int(row["label_value"]),
                _to_str(row["labeler"]),
                _to_str(row["source_file"]),
            )
            # Dedup against both the owner's pre-merge log AND rows already accepted in this batch
            # (a chained/replayed split file can carry two identical-provenance rows): add each
            # accepted key back so within-batch duplicates are skipped too (exact `appended`).
            ev = _event_key(row)
            if ev in existing_events:
                skipped_duplicate += 1
                continue
            existing_events.add(ev)
            matched_new.append(row)

        # 1) Append the new contributor human rows (append-only; resize + slice-assign, the
        #    tether.project.labels.set_curation_label pattern — /labels/table is 1-D resizable).
        appended = len(matched_new)
        if appended:
            new_block = np.zeros(appended, dtype=LABELS_DTYPE)
            for j, row in enumerate(matched_new):
                new_block[j] = row
            n0 = labels_table.shape[0]
            labels_table.resize((n0 + appended,))
            labels_table[n0:] = new_block

        # 2) Classify each matched molecule's contributor current decision vs the owner's, and adopt
        #    the non-conflicting new decisions into curation_label (never touch a conflict).
        adopted: list[str] = []
        agreements: list[str] = []
        conflicts: list[MergeConflict] = []
        for key, (decision, labeler, source_file) in latest_decision.items():
            if decision == _UNCURATED:
                continue  # contributor withdrew their decision (un-reject) — nothing to reconcile
            owner_label = int(mol_labels[owner_indices[key][0]])
            if owner_label == _UNCURATED:
                adopted.append(key)
                for i in owner_indices[key]:
                    r = mol_table[i]
                    r["curation_label"] = decision
                    mol_table[i] = r
            elif owner_label == decision:
                agreements.append(key)
            else:
                conflicts.append(
                    MergeConflict(
                        molecule_key=key,
                        owner_label=owner_label,
                        contributor_label=decision,
                        contributor_labeler=labeler,
                        contributor_source_file=source_file,
                    )
                )

    # 3) Central weight recompute over the merged set (own r+ open — after the append block closes).
    weights_recomputed = 0
    if recompute_weights:
        from tether.project.weighting import recompute_label_weights  # noqa: PLC0415

        weights_recomputed = recompute_label_weights(owner_path)

    return MergeReport(
        appended=appended,
        adopted=tuple(sorted(set(adopted))),
        agreements=tuple(sorted(set(agreements))),
        conflicts=tuple(conflicts),
        unmatched=tuple(sorted(unmatched)),
        ambiguous=tuple(sorted(ambiguous)),
        skipped_non_human=skipped_non_human,
        skipped_duplicate=skipped_duplicate,
        weights_recomputed=weights_recomputed,
    )
